### PR TITLE
Fix saving of persistent data files on different drives

### PR DESCRIPTION
**Pull request by DanielNoord**

### CODE REVIEW

**Comment by alkatar21** [comment]
I guess it is best to answer here?
I used the branch [stats-location](https://github.com/DanielNoord/pylint/tree/stats-location) and installed pylint on my end. Unfortunately there is an error this time:

```bash
(images) PS D:\Test> python.exe .\test_linter3.py D:\Test\test_linter.py
base=WindowsPath('D:/Test/test_linter.py')
pylint_home=WindowsPath('C:/Users/<username>/AppData/Local/pylint/pylint/Cache')
data_file=WindowsPath('C:/Users/<username>/AppData/Local/pylint/pylint/Cache/D_/_Test_test_linter.py_1.stats')
Unable to create file C:\Users\<username>\AppData\Local\pylint\pylint\Cache\D_\_Test_test_linter.py_1.stats: [Errno 2] No such file or directory: 'C:\\Users\\<username>\\AppData\\Local\\pylint\\pylint\\Cache\\D_\\_Test_test_linter.py_1.stats'
```

The problem is `D_\_Test_test_linter.py_1.stats` the folder `D_` does not exists. I am not sure whether you want to have the folder or name the file differently?

**Comment by DanielNoord** [comment]
Thsnk @alkatar21 for those pointers.

I have submitted a fix which replaces all "/"'s it encounters and added some additional tests. Please let me know if this does work!

**Comment by DanielNoord** [comment]
Thanks a lot for you help! I will get this submitted to upstream and merged asap. Should be available in the next release!

**Comment by DanielNoord** [comment]
Patch submitted as https://github.com/PyCQA/pylint/pull/6526.

Thanks for you help! I'm going to close this!

**Pull request closed without merging**
